baseURL = "https://gaahrdner.com"
languageCode = "en-us"
title = "Delirium"
theme = "beautifulhugo"
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-30931277-1"

[Params]
  logo = "/avatar.png"
  rss = true
  readingTime = true
  wordCount = true
  showRelatedPosts = true

[Author]
  name = "Phil Gardner"
  github = "gaahrdner"
  twitter = "gaahrdner"
  linkedin = "gaahrdner"
